package ai.neopsyke.agent.config

data class MemoryConfig(
    val maxShortTermContextChars: Int = 20_000,
    val maxShortTermContextPromptTokens: Int = 384,
    val scratchpad: ScratchpadConfig = ScratchpadConfig(),
    val longTermMemoryRecallMaxItems: Int = 4,
    val longTermMemoryRecallMaxChars: Int = 1_200,
    val longTermMemoryPromptCompressionEnabled: Boolean = true,
    val longTermMemoryPromptDialogueMaxChars: Int = 1_100,
    val longTermMemoryPromptRecallMaxChars: Int = 900,
    val longTermMemoryAssessEverySteps: Int = 16,
    val longTermMemoryAssessCooldownSteps: Int = 8,
    val longTermMemoryMinConfidence: Double = 0.65,
    val longTermMemoryMaxTokens: Int = 2048,
    val longTermMemoryMaxSummaryChars: Int = 320,
    val longTermMemoryForceAssessOnAllowedAction: Boolean = false,
    val longTermMemoryForceAssessOnTerminalAnswer: Boolean = true,
    val longTermMemoryParseFallbackDisableAfter: Int = 2,
    val longTermMemoryRecallEchoMinSummaryChars: Int = 16,
    val longTermMemoryRecallEchoMinTokenLength: Int = 3,
    val longTermMemoryRecallEchoMinTokenCount: Int = 4,
    val longTermMemoryRecallEchoTokenOverlapThreshold: Double = 0.85,
    val mcpMemoryCallTimeoutMs: Long = 8_000,
)
